// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBYia4yQ4jQsnHvgwHWBvx6cPrwBEFd0fs',
    appId: '1:854370730229:web:295a8657b847570b1585bc',
    messagingSenderId: '854370730229',
    projectId: 'clone-c23b2',
    authDomain: 'clone-c23b2.firebaseapp.com',
    storageBucket: 'clone-c23b2.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB-iaiE-s2jtJKaD9rw4GQuPcw1g5GXHeM',
    appId: '1:854370730229:android:75c9cd387eb187e91585bc',
    messagingSenderId: '854370730229',
    projectId: 'clone-c23b2',
    storageBucket: 'clone-c23b2.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD7CQ4CapyG3vNLUOsP8ZOB-OEIXe4PpAk',
    appId: '1:854370730229:ios:425f7eb594efbdb21585bc',
    messagingSenderId: '854370730229',
    projectId: 'clone-c23b2',
    storageBucket: 'clone-c23b2.appspot.com',
    iosBundleId: 'com.example.instagramClone',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD7CQ4CapyG3vNLUOsP8ZOB-OEIXe4PpAk',
    appId: '1:854370730229:ios:425f7eb594efbdb21585bc',
    messagingSenderId: '854370730229',
    projectId: 'clone-c23b2',
    storageBucket: 'clone-c23b2.appspot.com',
    iosBundleId: 'com.example.instagramClone',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBYia4yQ4jQsnHvgwHWBvx6cPrwBEFd0fs',
    appId: '1:854370730229:web:0bc23487918ac4ac1585bc',
    messagingSenderId: '854370730229',
    projectId: 'clone-c23b2',
    authDomain: 'clone-c23b2.firebaseapp.com',
    storageBucket: 'clone-c23b2.appspot.com',
  );
}
